SOURCE_DB = {
    "bbc": {
        "full_name": "BBC News",
        "credibility": 9.2,
        "bias": "Center",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "region": "Europe",
        "website": "https://bbc.com",
        "description": "UK public broadcaster with global reach. High editorial standards and independent journalism.",
        "type": "Public Broadcaster",
        "founded": 1922,
        "reliability": "Very High",
    },
    "bbc news": {
        "full_name": "BBC News",
        "credibility": 9.2,
        "bias": "Center",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "region": "Europe",
        "website": "https://bbc.com",
        "description": "UK public broadcaster with global reach. High editorial standards and independent journalism.",
        "type": "Public Broadcaster",
        "founded": 1922,
        "reliability": "Very High",
    },
    "reuters": {
        "full_name": "Reuters",
        "credibility": 9.5,
        "bias": "Center",
        "country": "Global",
        "flag": "🌍",
        "region": "Global",
        "website": "https://reuters.com",
        "description": "International news agency renowned for factual, unbiased reporting. Trusted by journalists worldwide.",
        "type": "News Agency",
        "founded": 1851,
        "reliability": "Very High",
    },
    "techcrunch": {
        "full_name": "TechCrunch",
        "credibility": 8.0,
        "bias": "Center",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://techcrunch.com",
        "description": "Leading technology and startup news publication covering Silicon Valley and global tech.",
        "type": "Digital Media",
        "founded": 2005,
        "reliability": "High",
    },
    "the guardian": {
        "full_name": "The Guardian",
        "credibility": 8.1,
        "bias": "Left-Leaning",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "region": "Europe",
        "website": "https://theguardian.com",
        "description": "British newspaper known for investigative journalism and progressive editorial stance.",
        "type": "Newspaper",
        "founded": 1821,
        "reliability": "High",
    },
    "al jazeera": {
        "full_name": "Al Jazeera",
        "credibility": 7.8,
        "bias": "Center",
        "country": "Qatar",
        "flag": "🇶🇦",
        "region": "Middle East",
        "website": "https://aljazeera.com",
        "description": "Qatar-based international news network covering global events with focus on Middle East and Africa.",
        "type": "TV / Digital",
        "founded": 1996,
        "reliability": "High",
    },
    "npr": {
        "full_name": "NPR",
        "credibility": 8.7,
        "bias": "Center-Left",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://npr.org",
        "description": "US public radio network with thorough, balanced reporting on national and international news.",
        "type": "Public Broadcaster",
        "founded": 1970,
        "reliability": "Very High",
    },
    "ars technica": {
        "full_name": "Ars Technica",
        "credibility": 8.5,
        "bias": "Center",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://arstechnica.com",
        "description": "In-depth technology, science, and policy journalism with expert-level analysis.",
        "type": "Digital Media",
        "founded": 1998,
        "reliability": "High",
    },
    "associated press": {
        "full_name": "Associated Press",
        "credibility": 9.3,
        "bias": "Center",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "Global",
        "website": "https://apnews.com",
        "description": "One of the world's oldest and most trusted news agencies with strict fact-checking standards.",
        "type": "News Agency",
        "founded": 1846,
        "reliability": "Very High",
    },
    "cnn": {
        "full_name": "CNN",
        "credibility": 6.8,
        "bias": "Left-Leaning",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://cnn.com",
        "description": "Major US cable news network with global distribution. Known for breaking news coverage.",
        "type": "TV / Digital",
        "founded": 1980,
        "reliability": "Moderate",
    },
    "fox news": {
        "full_name": "Fox News",
        "credibility": 5.9,
        "bias": "Right-Leaning",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://foxnews.com",
        "description": "US cable news network with conservative editorial stance and large viewership.",
        "type": "TV / Digital",
        "founded": 1996,
        "reliability": "Moderate",
    },
    "hacker news": {
        "full_name": "Hacker News",
        "credibility": 7.5,
        "bias": "Center",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://news.ycombinator.com",
        "description": "Community-curated tech and startup news aggregator by Y Combinator.",
        "type": "Community / Aggregator",
        "founded": 2007,
        "reliability": "High",
    },
    "wired": {
        "full_name": "Wired",
        "credibility": 8.2,
        "bias": "Center-Left",
        "country": "United States",
        "flag": "🇺🇸",
        "region": "North America",
        "website": "https://wired.com",
        "description": "In-depth coverage of technology, culture, science and its impact on society.",
        "type": "Magazine / Digital",
        "founded": 1993,
        "reliability": "High",
    },
}

_DEFAULT = {
    "full_name": None,
    "credibility": 6.0,
    "bias": "Unknown",
    "country": "Unknown",
    "flag": "🌐",
    "region": "Global",
    "website": None,
    "description": "Independent or unverified source.",
    "type": "Unknown",
    "founded": None,
    "reliability": "Unknown",
}


def get_source_info(source_name: str) -> dict:
    if not source_name:
        return {**_DEFAULT, "full_name": "Unknown"}

    key = source_name.lower().strip()

    if key in SOURCE_DB:
        return {**SOURCE_DB[key], "full_name": SOURCE_DB[key]["full_name"] or source_name}

    for db_key, info in SOURCE_DB.items():
        if db_key in key or key in db_key:
            return {**info, "full_name": info["full_name"] or source_name}

    return {**_DEFAULT, "full_name": source_name}
